# Generated by Django 4.2.4 on 2024-02-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='password',
            field=models.CharField(default='12345', max_length=122),
        ),
    ]
