# Generated by Django 4.2.4 on 2024-03-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P', '0002_login_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('host', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
            ],
        ),
    ]
