# Generated by Django 4.2.5 on 2024-04-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("P", "0004_visitor_city_visitor_visit_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="login",
            name="name",
        ),
        migrations.AddField(
            model_name="login",
            name="idval",
            field=models.CharField(default="1", max_length=122, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
