# Generated by Django 4.2.5 on 2024-04-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("P", "0006_userlogin_delete_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="vehiclenum",
            field=models.CharField(default="unknown", max_length=25),
        ),
        migrations.AlterField(
            model_name="userlogin",
            name="password",
            field=models.CharField(default="prithiv", max_length=122),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="city",
            field=models.CharField(default="unknown", max_length=50),
        ),
    ]
