# Generated by Django 4.2.5 on 2024-04-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("P", "0007_visitor_vehiclenum_alter_userlogin_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehiclenumber", models.CharField(max_length=255)),
                ("intime", models.CharField(default="unknown", max_length=255)),
                ("seatnum", models.CharField(max_length=10)),
                ("exit", models.CharField(max_length=10)),
                ("purpose", models.CharField(max_length=255)),
            ],
        ),
    ]
