# Generated by Django 4.2.5 on 2024-04-27 01:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("P", "0008_parkvehicle"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ParkVehicle",
            new_name="park_vehicle",
        ),
    ]
