# Generated by Django 4.2.5 on 2024-04-27 02:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("P", "0009_rename_parkvehicle_park_vehicle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="park_vehicle",
            name="purpose",
        ),
    ]
